
#define _GNU_SOURCE
#define HAVE_GETTIMEOFDAY_TZ_VOID
#define HAVE_PROGRAM_INVOCATION_SHORT_NAME
#define HAVE_OPEN64
#define HAVE_FOPEN64
#define HAVE_CONSTRUCTOR_ATTRIBUTE
#define HAVE_DESTRUCTOR_ATTRIBUTE


#define INTERCEPT_OPEN
#define INTERCEPT_OPEN64
#define INTERVEPT_OPENAT
#define INTERCEPT_FOPEN
#define INTERCEPT_FOPEN64
#define INTERCEPT_SYMLINK
#define INTERCEPT_SYMLINKAT
#define INTERCEPT_LINK
#define INTERCEPT_LINKAT
#define INTERCEPT_UNLINK
#define INTERCEPT_UNLINKAT
#define INTERCEPT_CHMOD
#define INTERCEPT_FCHMOD
#define INTERCEPT_FCHMODAT
#define INTERCEPT_EXECVE
#define INTERCEPT_EXECV
#define INTERCEPT_EXECVP
#define INTERCEPT_EXECVPE
#define INTERCEPT_EXECL
#define INTERCEPT_EXECLE
#define INTERCEPT_EXECLP
#define INTERCEPT_EXECLPE
#define INTERCEPT_EXECVEAT
#define INTERCEPT_POSIX_SPAWN
#define INTERCEPT_POSIX_SPAWNP
